import { timingSafeEqual } from 'crypto';
import type { FastifyPluginAsync, FastifyRequest, FastifySchemaCompiler } from 'fastify';
import { env } from '../../config/env.js';
import { logger } from '../../lib/logger.js';
import { buildWebhookSignature, parseWebhookSignature } from '../../lib/webhook-signature.js';
import { IngestSecurityAlertBodySchema, ingestSecurityAlertBodyJson } from './integrations.schema.js';
import * as integrationsService from './integrations.service.js';

function headerValue(request: FastifyRequest, headerName: string) {
  const value = request.headers[headerName];
  if (Array.isArray(value)) return value[0] ?? null;
  return value ?? null;
}

function secureEquals(expected: string, actual: string) {
  const expectedBuffer = Buffer.from(expected);
  const actualBuffer = Buffer.from(actual);
  if (expectedBuffer.length !== actualBuffer.length) return false;
  return timingSafeEqual(expectedBuffer, actualBuffer);
}

const passthroughValidator: FastifySchemaCompiler<unknown> = () => {
  return (data) => ({ value: data });
};

const integrationsRoutes: FastifyPluginAsync = async (fastify) => {
  fastify.post('/security-alerts/webhook', {
    // We verify signature against request body bytes semantics in-handler.
    // Route-level AJV validation is disabled here because global removeAdditional:'all'
    // mutates dynamic nested objects (e.g. context/metadata), breaking signatures.
    validatorCompiler: passthroughValidator,
    config: { rateLimit: { max: 120, timeWindow: '1 minute' } },
    schema: {
      tags: ['Integrations'],
      summary: 'Receive security alert webhook events',
      description:
        'System integration endpoint that receives real-time security alerts generated by this backend pipeline.',
      security: [],
      body: ingestSecurityAlertBodyJson,
      response: {
        202: {
          type: 'object',
          required: ['success', 'data'],
          properties: {
            success: { type: 'boolean', enum: [true] },
            data: {
              type: 'object',
              required: ['accepted', 'deliveryId'],
              properties: {
                accepted: { type: 'boolean', enum: [true] },
                deliveryId: { type: 'string' },
              },
            },
          },
        },
        401: { $ref: 'ApiError#' },
        422: { $ref: 'ApiError#' },
        429: { $ref: 'ApiError#' },
        503: { $ref: 'ApiError#' },
      },
    },
    handler: async (request, reply) => {
      const sourceHeader = headerValue(request, 'x-zikel-alert-source');
      if (sourceHeader !== 'security-alert-pipeline') {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Invalid security alert source header.',
          },
        });
      }

      const configuredSecret = env.SECURITY_ALERT_WEBHOOK_SHARED_SECRET;
      if (!configuredSecret) {
        logger.error({
          msg: 'Security alert webhook rejected because shared secret is not configured.',
          requestId: request.id,
        });
        return reply.status(503).send({
          success: false,
          error: {
            code: 'WEBHOOK_NOT_CONFIGURED',
            message: 'Security alert webhook receiver is not configured.',
          },
        });
      }

      const timestampHeader = headerValue(request, 'x-zikel-webhook-timestamp');
      const signatureHeader = headerValue(request, 'x-zikel-webhook-signature');
      if (!timestampHeader || !signatureHeader) {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Missing webhook signature headers.',
          },
        });
      }

      const timestampValue = Number.parseInt(timestampHeader, 10);
      if (!Number.isFinite(timestampValue)) {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Invalid webhook signature timestamp.',
          },
        });
      }

      const nowSeconds = Math.floor(Date.now() / 1_000);
      const drift = Math.abs(nowSeconds - timestampValue);
      if (drift > env.SECURITY_ALERT_WEBHOOK_MAX_DRIFT_SECONDS) {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Webhook signature timestamp is outside allowed drift window.',
          },
        });
      }

      const parsedSignature = parseWebhookSignature(signatureHeader);
      if (!parsedSignature) {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Invalid webhook signature format.',
          },
        });
      }

      const expectedSignature = buildWebhookSignature({
        payload: JSON.stringify(request.body ?? null),
        timestamp: timestampHeader,
        secret: configuredSecret,
      });
      if (!secureEquals(expectedSignature, parsedSignature.signature)) {
        return reply.status(401).send({
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Invalid webhook signature.',
          },
        });
      }

      const parse = IngestSecurityAlertBodySchema.safeParse(request.body);
      if (!parse.success) {
        const message = parse.error.issues[0]?.message ?? 'Validation error.';
        return reply.status(422).send({
          success: false,
          error: { code: 'VALIDATION_ERROR', message },
        });
      }

      const data = await integrationsService.receiveSecurityAlertWebhook(parse.data, {
        requestId: request.id,
        sourceHeader,
      });

      return reply.status(202).send({
        success: true,
        data,
      });
    },
  });
};

export default integrationsRoutes;
